#!/bin/sh

export PICO_SDK_PATH=/mnt/datassd/2023/pico/pico-sdk/
rm -rf build
mkdir build
cd build
cmake .. -DPICO_BOARD=pico_w \
         -DWIFI_SSID=MyWifi \
         -DWIFI_PASSWORD=MyPassword
if [ $? != 0 ]; then exit 1; fi
cd ..

make -C build
if [ $? != 0 ]; then exit 1; fi

openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program build/morningtown.elf verify reset exit"
