#!/bin/sh

export PICO_SDK_PATH=/mnt/datassd/2023/pico/pico-sdk/
rm -rf build
mkdir build
cd build
cmake .. -DPICO_BOARD=pico_w \
         -DWIFI_SSID=MyWifi \
         -DWIFI_PASSWORD=MyPassword
cd ..
make -C build

